"""add restrict fk on user_books book_id

Revision ID: ccb619663b02
Revises: 2931698c8051
Create Date: 2026-03-28 12:08:41.415587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccb619663b02'
down_revision: Union[str, None] = '2931698c8051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_books_book_id_fkey', 'user_books', type_='foreignkey')
    op.create_foreign_key(None, 'user_books', 'books', ['book_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_books', type_='foreignkey')
    op.create_foreign_key('user_books_book_id_fkey', 'user_books', 'books', ['book_id'], ['id'])
    # ### end Alembic commands ###
